/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package haritmetiikka.kayttoliittyma.miinus;

import haritmetiikka.rajapinta.Tehtava;

/**
 *
 * @author poplinus
 */
public class MiinusIkkuna extends javax.swing.JFrame {

    public Tehtava tehtava = new Tehtava();

    int vastaus;

    /**
     * Konstruktori joka muotoilee MiinusVastausIkkunan johon tuodaan olemassa
     * oleva Tehtava-luokka.
     */
    public MiinusIkkuna(Tehtava tehtava) {
        initComponents();
        this.tehtava = tehtava;
        
        ekaLukuLabel.setText(this.tehtava.getEkaLuku() + " - " + this.tehtava.getMiinusTokaLuku()+ " = ");
    }

    /**
     * Konsistori joka muotoilee SuommaVastausIkkunan.
     */
    public MiinusIkkuna() {
        initComponents();

        ekaLukuLabel.setText(tehtava.getEkaLuku() + " - " + tehtava.getMiinusTokaLuku() + " = ");
   
     
    }

    /**
     * Metodi muotoilee ikkunan ja elementit This method is called from within
     * the constructor to initialize the form. WARNING: Do NOT modify this code.
     * The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uusiLasku = new javax.swing.JButton();
        lopeta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ekaLukuLabel = new javax.swing.JLabel();
        vastausTextField = new javax.swing.JTextField();
        syottoVirheJLabel = new javax.swing.JLabel();
        vastaaJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Miinus harjoitus");

        uusiLasku.setText("UusiLasku");
        uusiLasku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uusiLaskuActionPerformed(evt);
            }
        });

        lopeta.setText("Lopeta");
        lopeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaActionPerformed(evt);
            }
        });

        ekaLukuLabel.setText("ekaLuku");

        vastausTextField.setText("?");
        vastausTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vastausTextFieldActionPerformed(evt);
            }
        });

        syottoVirheJLabel.setForeground(new java.awt.Color(255, 0, 0));

        vastaaJButton.setText("Vastaa");
        vastaaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vastaaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(syottoVirheJLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ekaLukuLabel)
                        .addGap(26, 26, 26)
                        .addComponent(vastausTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(vastaaJButton)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vastausTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ekaLukuLabel)
                        .addComponent(vastaaJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(syottoVirheJLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uusiLasku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lopeta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uusiLasku)
                    .addComponent(lopeta))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodi avaa uuden summaikkunan ja sulkee olemassa olevan. Näin alkaa uusi
     * lasku.
     *
     * @param evt
     */
    private void uusiLaskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uusiLaskuActionPerformed

        new MiinusIkkuna().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_uusiLaskuActionPerformed
    /**
     * Metodi avaa uuden MiinusVastausIkkunan ja vie siihen olemassa olevan
     * Tehtava-luokan olion.
     *
     * @param evt
     */
    private void vastaaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vastaaJButtonActionPerformed
        try {
            this.vastaus = Integer.parseInt(vastausTextField.getText());
            new MiinusVastausIkkuna(this.tehtava, this.vastaus).setVisible(true);

            //  new MiinusIkkuna().setVisible(true);
//    
            this.dispose();
        } catch (Exception e) {

            this.syottoVirheJLabel.setText("Syötä kokonaisluku tai lopeta");

        }

    }//GEN-LAST:event_vastaaJButtonActionPerformed
    /**
     * Metodi lopettaa Yhteenlaskuharjoituksen.
     *
     * @param evt
     */
    private void lopetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetaActionPerformed
        // javax.swing.WindowConstants.EXIT_ON_CLOSE;
        this.dispose();
    }//GEN-LAST:event_lopetaActionPerformed

    private void vastausTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vastausTextFieldActionPerformed

    }//GEN-LAST:event_vastausTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ekaLukuLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lopeta;
    private javax.swing.JLabel syottoVirheJLabel;
    private javax.swing.JButton uusiLasku;
    private javax.swing.JButton vastaaJButton;
    private javax.swing.JTextField vastausTextField;
    // End of variables declaration//GEN-END:variables
}
