/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package haritmetiikka.kayttoliittyma;

import haritmetiikka.rajapinta.Tehtava;
import java.lang.Process.*;
/**
 *
 * @author poplinus
 */
public class KoeSummaIkkuna extends javax.swing.JFrame {

    Tehtava koeTehtava = new Tehtava();
    int tehtavaNro;
    int koeTehtaviaOikein;
    int vastaus;
    String syottoVirheTeksti;

/*
     * Creates new form SummaKoeIkkuna
     */
    public KoeSummaIkkuna(int tehtavaNro,int koeTehtaviaOikein, String syottoVirheTeksti) {
       initComponents();
       this.tehtavaNro = tehtavaNro;
       this.koeTehtaviaOikein= koeTehtaviaOikein;
       this.syottoVirheTeksti = syottoVirheTeksti;
       ekaLukuLabel.setText(String.valueOf(koeTehtava.getEkaLuku()));
       tokaLukuLabel.setText(String.valueOf(koeTehtava.getTokaLuku()));
       tehtavaNroLabel.setText(this.tehtavaNro+". tehtävä");
       syottoVirheJLabel.setText(this.syottoVirheTeksti);
    
       
    }
    
    
    public static int laskuri(int nro){
       return nro++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ekaLukuLabel = new javax.swing.JLabel();
        tokaLukuLabel = new javax.swing.JLabel();
        vastausButton = new javax.swing.JButton();
        vastausTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tehtavaNroLabel = new javax.swing.JLabel();
        lopetaButton = new javax.swing.JButton();
        syottoVirheJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ekaLukuLabel.setText("jLabel1");

        tokaLukuLabel.setText("jLabel2");

        vastausButton.setText("Vastaa");
        vastausButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vastausButtonActionPerformed(evt);
            }
        });

        vastausTextField.setText("?");
        vastausTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vastausTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("+");

        jLabel4.setText("=");

        jLabel5.setText("Yhteenlaskukoe. Yhteensä 10 tehtävää.");

        tehtavaNroLabel.setText("jLabel1");

        lopetaButton.setText("Lopeta");
        lopetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tehtavaNroLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(ekaLukuLabel)
                                .addGap(27, 27, 27)
                                .addComponent(tokaLukuLabel)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(vastausTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(syottoVirheJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(vastausButton)
                        .addGap(76, 76, 76)))
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lopetaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tehtavaNroLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekaLukuLabel)
                    .addComponent(tokaLukuLabel)
                    .addComponent(vastausButton)
                    .addComponent(vastausTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(syottoVirheJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lopetaButton)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vastausTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vastausTextFieldActionPerformed
  
    }//GEN-LAST:event_vastausTextFieldActionPerformed

   private void vaaraSyotto(){
      
       KoeSummaIkkuna koeSummaIkkuna = new KoeSummaIkkuna(this.tehtavaNro,this.koeTehtaviaOikein,"virhesyotto");
       new SyottoVirheIkkuna().setVisible(true);
       this.dispose();
       
   }
   

    
    private void vastausButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vastausButtonActionPerformed
     try {
           this.vastaus = Integer.parseInt(vastausTextField.getText());
         System.out.println("väärä paikka");
                 
               this.tehtavaNro++;
        
        if(koeTehtava.getOikein("summa", koeTehtava.getEkaLuku(), koeTehtava.getTokaLuku(),vastaus)){
        koeTehtaviaOikein++;
        
            System.out.println("koeTehtaviaOikein laskuri");
        }
            
        System.out.println(koeTehtaviaOikein);    
        if(tehtavaNro<=10){    
            System.out.println("uusi tehtava");
       
        new KoeSummaIkkuna(tehtavaNro,koeTehtaviaOikein,"Uusi tehtava").setVisible(true);
        this.dispose();}
        else{new KoeTulosIkkuna(tehtavaNro,koeTehtaviaOikein).setVisible(true);
         this.dispose();          
        }
     }
      catch (Exception e) {
         this.dispose();
        new KoeSummaIkkuna(tehtavaNro,koeTehtaviaOikein,"Syötä kokonaisluku tai lopeta").setVisible(true);
          
          System.out.println("syöttö väärin");
        // while(Integer.parseInt(vastausTextField.getText())){
             
         //}
    }


        //this.dispose();
         
         
       //  new KoeSummaIkkuna(tehtavaNro,koeTehtaviaOikein,"Syötä kokonailsluku tai lopeta").setVisible(true);  
     
      
        
     
     
   
         
    }//GEN-LAST:event_vastausButtonActionPerformed

    private void lopetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetaButtonActionPerformed
      this.dispose();
   
    }//GEN-LAST:event_lopetaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ekaLukuLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lopetaButton;
    private javax.swing.JLabel syottoVirheJLabel;
    private javax.swing.JLabel tehtavaNroLabel;
    private javax.swing.JLabel tokaLukuLabel;
    private javax.swing.JButton vastausButton;
    private javax.swing.JTextField vastausTextField;
    // End of variables declaration//GEN-END:variables

}

    /*
        private void uusiTehtava(int tehtavaNro){
            
        this.tehtavaNro = tehtavaNro;
        
    }
    */
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SummaKoeIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SummaKoeIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SummaKoeIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SummaKoeIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SummaKoeIkkuna().setVisible(true);
//            }
//        });
//    }

