/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package haritmetiikka.kayttoliittyma;

import haritmetiikka.rajapinta.Tehtava;

/**
 *
 * @author poplinus
 */
public class SummaVastausIkkuna extends javax.swing.JFrame {

    private Tehtava tehtava;
    private int vastaus;

    /**
     * Metodi rakentaa SummaVastausIkkunan
     *
     * @param summaTehtava SummaIkkunasta tuotu olio, jossa on mm. jo arvotut
     * luvut
     * @param vastaus SummaIkkunassa käyttäjän antama laskun vastaus
     */

    public SummaVastausIkkuna(Tehtava summaTehtava, int vastaus) {
        initComponents();
        this.tehtava = summaTehtava;
        this.vastaus = vastaus;
        oikeaVastausLabel.setText("Oikea vastaus: " + String.valueOf(summaTehtava.getOikeaVastaus("summa", summaTehtava.getEkaLuku(), summaTehtava.getTokaLuku())));
        if (summaTehtava.getOikein("summa", summaTehtava.getEkaLuku(), summaTehtava.getTokaLuku(), vastaus)) {
            vastausOikeinLabel.setText("Vastasit oikein");

        } else {
            vastausOikeinLabel.setText("Vastasit väärin");
        }
//      vastausOikeinLabel.setText(String.valueOf(summaTehtava.getOikein("summa", summaTehtava.getEkaLuku(), summaTehtava.getTokaLuku(), vastaus)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oikeaVastausLabel = new javax.swing.JLabel();
        vastausOikeinLabel = new javax.swing.JLabel();
        uusiLaskuButton = new javax.swing.JButton();
        lopetaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        oikeaVastausLabel.setText("jLabel1");

        vastausOikeinLabel.setText("jLabel2");

        uusiLaskuButton.setText("Uusi Lasku");
        uusiLaskuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uusiLaskuButtonActionPerformed(evt);
            }
        });

        lopetaButton.setText("Kokeile uudelleen");
        lopetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lopetaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(oikeaVastausLabel)
                        .addGap(48, 48, 48)
                        .addComponent(vastausOikeinLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(uusiLaskuButton)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oikeaVastausLabel)
                            .addComponent(vastausOikeinLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(uusiLaskuButton)))
                .addGap(18, 18, 18)
                .addComponent(lopetaButton)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Nappi joka sulkee SummaVastausIkkunan ja tekee uuden SummaIkkunan (uusi
     * lasku)
     *
     * @param evt
     */
    private void uusiLaskuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uusiLaskuButtonActionPerformed

        new SummaIkkuna().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_uusiLaskuButtonActionPerformed
    /**
     * Nappi joka sulkee SummaVastausIkkunan
     *
     * @param evt
     */

    private void lopetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetaButtonActionPerformed
        this.dispose();
        // this.setVisible(false);
    }//GEN-LAST:event_lopetaButtonActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SummaVastausIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SummaVastausIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SummaVastausIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SummaVastausIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//   //             new SummaVastausIkkuna().setVisible(true);
//
//            }
//
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lopetaButton;
    private javax.swing.JLabel oikeaVastausLabel;
    private javax.swing.JButton uusiLaskuButton;
    private javax.swing.JLabel vastausOikeinLabel;
    // End of variables declaration//GEN-END:variables
}
