/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package haritmetiikka.kayttoliittyma;

import haritmetiikka.rajapinta.Tehtava;

/**
 *
 * @author poplinus
 */
public class SummaVastausIkkuna extends javax.swing.JFrame {

    private Tehtava tehtava;
    private int vastaus;

    /**
     * Metodi rakentaa SummaVastausIkkunan
     *
     * @param tehtava SummaIkkunasta tuotu olio, jossa on mm. jo arvotut luvut
     * @param vastaus SummaIkkunassa käyttäjän antama laskun vastaus
     */
    public SummaVastausIkkuna(Tehtava tehtava, int vastaus) {
        initComponents();
        this.tehtava = tehtava;
        this.vastaus = vastaus;
        oikeaVastausLabel.setText("Oikea vastaus: " + String.valueOf(tehtava.getOikeaVastaus("summa", tehtava.getEkaLuku(), tehtava.getTokaLuku())));
        if (tehtava.getOikein("summa", tehtava.getEkaLuku(), tehtava.getTokaLuku(), vastaus)) {
            vastausOikeinLabel.setText("Vastasit oikein");
        } else {
            vastausOikeinLabel.setText("Vastasit väärin");
        }
//      vastausOikeinLabel.setText(String.valueOf(tehtava.getOikein("summa", tehtava.getEkaLuku(), tehtava.getTokaLuku(), vastaus)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oikeaVastausLabel = new javax.swing.JLabel();
        vastausOikeinLabel = new javax.swing.JLabel();
        uusiLaskuButton = new javax.swing.JButton();
        kokeileUudelleenJButton = new javax.swing.JButton();
        lopetaJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        oikeaVastausLabel.setText("jLabel1");

        vastausOikeinLabel.setText("jLabel2");

        uusiLaskuButton.setText("Uusi Lasku");
        uusiLaskuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uusiLaskuButtonActionPerformed(evt);
            }
        });

        kokeileUudelleenJButton.setText("Kokeile uudelleen");
        kokeileUudelleenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kokeileUudelleenJButtonActionPerformed(evt);
            }
        });

        lopetaJButton.setText("Lopeta");
        lopetaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(oikeaVastausLabel)
                        .addGap(48, 48, 48)
                        .addComponent(vastausOikeinLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(uusiLaskuButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lopetaJButton)
                            .addComponent(kokeileUudelleenJButton))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oikeaVastausLabel)
                            .addComponent(vastausOikeinLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(uusiLaskuButton)))
                .addGap(18, 18, 18)
                .addComponent(kokeileUudelleenJButton)
                .addGap(34, 34, 34)
                .addComponent(lopetaJButton)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Nappi joka sulkee SummaVastausIkkunan ja tekee uuden SummaIkkunan (uusi
     * lasku)
     *
     * @param evt
     */
    private void uusiLaskuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uusiLaskuButtonActionPerformed
        new SummaIkkuna().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_uusiLaskuButtonActionPerformed
    /**
     * Nappi joka sulkee SummaVastausIkkunan
     *
     * @param evt
     */

    private void kokeileUudelleenJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kokeileUudelleenJButtonActionPerformed
        new SummaIkkuna(this.tehtava).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kokeileUudelleenJButtonActionPerformed

    private void lopetaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetaJButtonActionPerformed
        new StartIkkuna().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lopetaJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton kokeileUudelleenJButton;
    private javax.swing.JButton lopetaJButton;
    private javax.swing.JLabel oikeaVastausLabel;
    private javax.swing.JButton uusiLaskuButton;
    private javax.swing.JLabel vastausOikeinLabel;
    // End of variables declaration//GEN-END:variables
}
